export const fakeDatas = [
  {
    firstName: "Norina",
    lastName: "Castillo",
    dateOfStart: "6/15/2023",
    jobDepartment: "Engineering",
    dateOfBirth: "5/25/2023",
    street: "20210 Prairieview Circle",
    city: "Paterson",
    stateAbbreviation: "NJ",
    zipCode: "07522",
  },
  {
    firstName: "Gabriellia",
    lastName: "Kleinsinger",
    dateOfStart: "1/9/2023",
    jobDepartment: "Services",
    dateOfBirth: "11/6/2023",
    street: "91364 Red Cloud Center",
    city: "Olympia",
    stateAbbreviation: "WA",
    zipCode: "98506",
  },
  {
    firstName: "Tommie",
    lastName: "Garvin",
    dateOfStart: "9/25/2023",
    jobDepartment: "Research and Development",
    dateOfBirth: "7/17/2023",
    street: "423 Golf Course Way",
    city: "Springfield",
    stateAbbreviation: "IL",
    zipCode: "62764",
  },
  {
    firstName: "Granthem",
    lastName: "Walkling",
    dateOfStart: "12/3/2022",
    jobDepartment: "Research and Development",
    dateOfBirth: "12/30/2022",
    street: "075 Mendota Drive",
    city: "Naples",
    stateAbbreviation: "FL",
    zipCode: "33963",
  },
  {
    firstName: "Christoforo",
    lastName: "Giraudoux",
    dateOfStart: "10/19/2023",
    jobDepartment: "Engineering",
    dateOfBirth: "12/11/2022",
    street: "7539 Hoffman Road",
    city: "New Haven",
    stateAbbreviation: "CT",
    zipCode: "06520",
  },
  {
    firstName: "Thorstein",
    lastName: "Westlake",
    dateOfStart: "7/31/2023",
    jobDepartment: "Marketing",
    dateOfBirth: "8/23/2023",
    street: "6970 Kipling Way",
    city: "Milwaukee",
    stateAbbreviation: "WI",
    zipCode: "53277",
  },
  {
    firstName: "Latisha",
    lastName: "Lidgey",
    dateOfStart: "2/2/2023",
    jobDepartment: "Services",
    dateOfBirth: "8/23/2023",
    street: "85 Everett Lane",
    city: "Tacoma",
    stateAbbreviation: "WA",
    zipCode: "98442",
  },
  {
    firstName: "Caralie",
    lastName: "Curedale",
    dateOfStart: "8/1/2023",
    jobDepartment: "Business Development",
    dateOfBirth: "12/11/2022",
    street: "856 Summit Alley",
    city: "Seattle",
    stateAbbreviation: "WA",
    zipCode: "98133",
  },
  {
    firstName: "Barri",
    lastName: "Cardenas",
    dateOfStart: "10/13/2023",
    jobDepartment: "Sales",
    dateOfBirth: "3/16/2023",
    street: "5 2nd Court",
    city: "Tyler",
    stateAbbreviation: "TX",
    zipCode: "75705",
  },
  {
    firstName: "Nonnah",
    lastName: "Bartolomucci",
    dateOfStart: "9/9/2023",
    jobDepartment: "Accounting",
    dateOfBirth: "3/19/2023",
    street: "0 Kropf Way",
    city: "Dulles",
    stateAbbreviation: "VA",
    zipCode: "20189",
  },
  {
    firstName: "Jeromy",
    lastName: "Pullinger",
    dateOfStart: "7/27/2023",
    jobDepartment: "Marketing",
    dateOfBirth: "4/17/2023",
    street: "92 Springview Circle",
    city: "San Diego",
    stateAbbreviation: "CA",
    zipCode: "92191",
  },
  {
    firstName: "Adda",
    lastName: "Candey",
    dateOfStart: "10/28/2023",
    jobDepartment: "Sales",
    dateOfBirth: "9/24/2023",
    street: "91130 Shasta Court",
    city: "Saint Paul",
    stateAbbreviation: "MN",
    zipCode: "55114",
  },
  {
    firstName: "Clive",
    lastName: "Linneman",
    dateOfStart: "3/23/2023",
    jobDepartment: "Legal",
    dateOfBirth: "5/4/2023",
    street: "03226 Waxwing Road",
    city: "El Paso",
    stateAbbreviation: "TX",
    zipCode: "88579",
  },
  {
    firstName: "Fern",
    lastName: "L'Archer",
    dateOfStart: "5/25/2023",
    jobDepartment: "Research and Development",
    dateOfBirth: "4/4/2023",
    street: "52 Golf View Terrace",
    city: "San Francisco",
    stateAbbreviation: "CA",
    zipCode: "94154",
  },
  {
    firstName: "Cahra",
    lastName: "Howel",
    dateOfStart: "5/3/2023",
    jobDepartment: "Marketing",
    dateOfBirth: "9/25/2023",
    street: "1551 Heffernan Court",
    city: "Denver",
    stateAbbreviation: "CO",
    zipCode: "80249",
  },
  {
    firstName: "Urbanus",
    lastName: "Claxson",
    dateOfStart: "3/26/2023",
    jobDepartment: "Human Resources",
    dateOfBirth: "8/13/2023",
    street: "98341 Spohn Junction",
    city: "Shawnee Mission",
    stateAbbreviation: "KS",
    zipCode: "66210",
  },
  {
    firstName: "Karlan",
    lastName: "Enric",
    dateOfStart: "11/2/2023",
    jobDepartment: "Business Development",
    dateOfBirth: "5/6/2023",
    street: "9 Fairview Court",
    city: "Fresno",
    stateAbbreviation: "CA",
    zipCode: "93715",
  },
  {
    firstName: "Emmaline",
    lastName: "Gilliam",
    dateOfStart: "1/16/2023",
    jobDepartment: "Support",
    dateOfBirth: "7/18/2023",
    street: "04651 Mockingbird Terrace",
    city: "East Saint Louis",
    stateAbbreviation: "IL",
    zipCode: "62205",
  },
  {
    firstName: "Ursula",
    lastName: "Navarro",
    dateOfStart: "4/15/2023",
    jobDepartment: "Training",
    dateOfBirth: "3/1/2023",
    street: "0882 Forest Trail",
    city: "Albany",
    stateAbbreviation: "NY",
    zipCode: "12232",
  },
  {
    firstName: "Carley",
    lastName: "Jovanovic",
    dateOfStart: "8/12/2023",
    jobDepartment: "Human Resources",
    dateOfBirth: "1/24/2023",
    street: "661 Paget Road",
    city: "Tacoma",
    stateAbbreviation: "WA",
    zipCode: "98447",
  },
  {
    firstName: "Carley",
    lastName: "Jovanovic",
    dateOfStart: "8/12/2023",
    jobDepartment: "Human Resources",
    dateOfBirth: "1/24/2023",
    street: "661 Paget Road",
    city: "Tacoma",
    stateAbbreviation: "WA",
    zipCode: "98447",
  },
];
